// Products data

export const products = [
  {
    id: 1,
    title: "Gold Jewelry",
    category: "jewelry",
    price: 25.99,
    img: "./assets/9.png",
  },
  {
    id: 2,
    title: "Dotted Shirt",
    category: "shirt",
    price: 15.99,
    img: "./assets/7.png",
  },
  {
    id: 3,
    title: "Cool Shirt",
    category: "shirt",
    price: 15.99,
    img: "./assets/8.png",
  },
  {
    id: 4,
    title: "Wedding Gown",
    category: "gown",
    price: 15.99,
    img: "./assets/6.png",
  },
  {
    id: 5,
    title: "Diamon Jewelry",
    category: "jewelry",
    price: 15.99,
    img: "./assets/10.png",
  },
  {
    id: 6,
    title: "Golden Jewelries",
    category: "jewelry",
    price: 15.99,
    img: "./assets/11.png",
  },
  {
    id: 7,
    title: "Analog Watch",
    category: "watch",
    price: 15.99,
    img: "./assets/1.png",
  },
  {
    id: 8,
    title: "Digital Watch",
    category: "watch",
    price: 15.99,
    img: "./assets/13.png",
  },
  {
    id: 9,
    title: "Button Shirt",
    category: "shirt",
    price: 35.99,
    img: "./assets/5.png",
  },
  {
    id: 10,
    title: "Sport Watch",
    category: "watch",
    price: 35.99,
    img: "./assets/2.png",
  },
  {
    id: 11,
    title: "Polo shirt",
    category: "shirt",
    price: 35.99,
    img: "./assets/3.png",
  },
  {
    id: 12,
    title: "Polo Shirt",
    category: "shirt",
    price: 35.99,
    img: "./assets/4.png",
  },
];
